name = "scf-com-proxy"
main = "scf-com-proxy.js"
compatibility_date = "2024-11-01"
workers_dev = true

[[routes]]
pattern = "www.sensorcrashfix.com/*"
zone_name = "sensorcrashfix.com"

[[routes]]
pattern = "sensorcrashfix.com/*"
zone_name = "sensorcrashfix.com"

[[routes]]
pattern = "www.sensorcrashfix.com.br/*"
zone_name = "sensorcrashfix.com.br"

[[routes]]
pattern = "sensorcrashfix.com.br/*"
zone_name = "sensorcrashfix.com.br"
